-- ============================================================================
-- AGENTIC AI BRAIN - DATABASE SCHEMA
-- ============================================================================
-- Version: 1.0.0
-- Created: November 23, 2025
-- Description: Complete database schema for the Agentic AI Brain system
-- ============================================================================

-- ============================================================================
-- 1. CHAT SESSIONS & MESSAGES
-- ============================================================================

-- Main chat sessions table
CREATE TABLE IF NOT EXISTS agent_chat_sessions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  client_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL,
  title VARCHAR(500) NOT NULL,
  folder VARCHAR(255),
  tags TEXT[],
  is_archived BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE agent_chat_sessions IS 'Chat sessions for the Agentic AI Brain';
COMMENT ON COLUMN agent_chat_sessions.user_id IS 'User who owns this session';
COMMENT ON COLUMN agent_chat_sessions.client_id IS 'Optional client context';
COMMENT ON COLUMN agent_chat_sessions.project_id IS 'Optional project context';
COMMENT ON COLUMN agent_chat_sessions.folder IS 'Organizational folder name';
COMMENT ON COLUMN agent_chat_sessions.tags IS 'Array of tags for categorization';

-- Chat messages with streaming support
CREATE TABLE IF NOT EXISTS agent_chat_messages (
  id SERIAL PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES agent_chat_sessions(id) ON DELETE CASCADE,
  role VARCHAR(20) NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content TEXT NOT NULL,
  model_used VARCHAR(100),
  tokens_used INTEGER,
  plan_json JSONB,
  tool_calls JSONB,
  sources JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE agent_chat_messages IS 'Individual messages in chat sessions';
COMMENT ON COLUMN agent_chat_messages.model_used IS 'AI model used (e.g., claude-sonnet-4-20250514)';
COMMENT ON COLUMN agent_chat_messages.plan_json IS 'Execution plan if this is a plan message';
COMMENT ON COLUMN agent_chat_messages.tool_calls IS 'Array of tools called during execution';
COMMENT ON COLUMN agent_chat_messages.sources IS 'Data sources with confidence scores';

-- ============================================================================
-- 2. ARTIFACTS (GENERATED CONTENT)
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_artifacts (
  id SERIAL PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES agent_chat_sessions(id) ON DELETE CASCADE,
  message_id INTEGER REFERENCES agent_chat_messages(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL,
  title VARCHAR(500),
  content JSONB,
  file_path TEXT,
  google_doc_id VARCHAR(255),
  google_doc_url TEXT,
  version INTEGER DEFAULT 1,
  parent_artifact_id INTEGER REFERENCES agent_artifacts(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE agent_artifacts IS 'Documents, tables, charts, and other content generated by the agent';
COMMENT ON COLUMN agent_artifacts.type IS 'Artifact type: document, table, chart, pdf, slide, etc.';
COMMENT ON COLUMN agent_artifacts.content IS 'Structured content (JSON format)';
COMMENT ON COLUMN agent_artifacts.parent_artifact_id IS 'Parent artifact ID for versioning/forking';

-- ============================================================================
-- 3. TEMPLATES
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_templates (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  logo_path TEXT,
  colors JSONB,
  fonts JSONB,
  header_footer JSONB,
  cover_layout JSONB,
  template_file_path TEXT,
  variables JSONB,
  is_active BOOLEAN DEFAULT true,
  version INTEGER DEFAULT 1,
  tags TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE agent_templates IS 'Brand templates for document generation';
COMMENT ON COLUMN agent_templates.type IS 'Template type: proposal, report, email, presentation, etc.';
COMMENT ON COLUMN agent_templates.colors IS 'Brand colors: { primary: "#...", secondary: "#..." }';
COMMENT ON COLUMN agent_templates.fonts IS 'Font settings: { heading: "...", body: "..." }';
COMMENT ON COLUMN agent_templates.variables IS 'Array of {{placeholder}} variable names';

-- ============================================================================
-- 4. COLLABORATION & PRESENCE
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_session_presence (
  id SERIAL PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES agent_chat_sessions(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  is_active BOOLEAN DEFAULT true,
  is_typing BOOLEAN DEFAULT false,
  last_seen TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(session_id, user_id)
);

COMMENT ON TABLE agent_session_presence IS 'Real-time presence tracking for collaborative sessions';

-- ============================================================================
-- 5. FEEDBACK & LEARNING
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_feedback (
  id SERIAL PRIMARY KEY,
  message_id INTEGER NOT NULL REFERENCES agent_chat_messages(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rating INTEGER CHECK (rating IN (1, -1)),
  categories JSONB,
  text_feedback TEXT,
  training_instruction TEXT,
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  approved_by INTEGER REFERENCES users(id),
  approved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE agent_feedback IS 'User feedback for agent responses';
COMMENT ON COLUMN agent_feedback.rating IS '1 = thumbs up, -1 = thumbs down';
COMMENT ON COLUMN agent_feedback.categories IS 'Detailed ratings: { accuracy: 5, tone: 4, completeness: 3 }';
COMMENT ON COLUMN agent_feedback.training_instruction IS 'User instruction for what agent should learn';

-- User/advisor preferences (long-term memory)
CREATE TABLE IF NOT EXISTS agent_user_preferences (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  preference_key VARCHAR(255) NOT NULL,
  preference_value TEXT NOT NULL,
  learned_from_feedback BOOLEAN DEFAULT false,
  confidence_score FLOAT DEFAULT 0.5,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, preference_key)
);

COMMENT ON TABLE agent_user_preferences IS 'Learned user preferences for personalization';
COMMENT ON COLUMN agent_user_preferences.preference_key IS 'e.g., tone, format_preference, email_style';
COMMENT ON COLUMN agent_user_preferences.confidence_score IS 'Confidence in this preference (0-1)';

-- ============================================================================
-- 6. BACKGROUND JOBS
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_background_jobs (
  id SERIAL PRIMARY KEY,
  session_id INTEGER REFERENCES agent_chat_sessions(id) ON DELETE SET NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  job_type VARCHAR(100) NOT NULL,
  status VARCHAR(20) DEFAULT 'queued' CHECK (status IN ('queued', 'processing', 'completed', 'failed')),
  input_data JSONB,
  output_data JSONB,
  error_message TEXT,
  retry_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ
);

COMMENT ON TABLE agent_background_jobs IS 'Queue for long-running tasks (video processing, etc.)';
COMMENT ON COLUMN agent_background_jobs.job_type IS 'Type: video_transcription, pdf_generation, etc.';

-- ============================================================================
-- 7. NOTIFICATIONS
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_notification_preferences (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  job_complete_email BOOLEAN DEFAULT false,
  job_complete_platform BOOLEAN DEFAULT true,
  job_complete_push BOOLEAN DEFAULT false,
  weekly_digest_email BOOLEAN DEFAULT true,
  weekly_digest_platform BOOLEAN DEFAULT true,
  digest_preferences JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE agent_notification_preferences IS 'User notification preferences';
COMMENT ON COLUMN agent_notification_preferences.digest_preferences IS 'What to include in weekly digest';

CREATE TABLE IF NOT EXISTS agent_notifications (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT,
  link TEXT,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  read_at TIMESTAMPTZ
);

COMMENT ON TABLE agent_notifications IS 'In-platform notifications';

-- ============================================================================
-- 8. WEEKLY DIGESTS
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_weekly_digests (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  week_start DATE NOT NULL,
  week_end DATE NOT NULL,
  content JSONB NOT NULL,
  email_sent BOOLEAN DEFAULT false,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE agent_weekly_digests IS 'Weekly activity summaries';
COMMENT ON COLUMN agent_weekly_digests.content IS 'Digest data: chats, tasks, documents, insights';

-- ============================================================================
-- 9. PINECONE SYNC TRACKING
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_pinecone_sync (
  id SERIAL PRIMARY KEY,
  source_type VARCHAR(50) NOT NULL,
  source_id INTEGER NOT NULL,
  pinecone_id VARCHAR(255) NOT NULL,
  embedding_model VARCHAR(100) DEFAULT 'text-embedding-3-small',
  last_synced TIMESTAMPTZ DEFAULT NOW(),
  metadata JSONB,
  UNIQUE(source_type, source_id)
);

COMMENT ON TABLE agent_pinecone_sync IS 'Tracks what content is synced to Pinecone vector DB';
COMMENT ON COLUMN agent_pinecone_sync.source_type IS 'Type: proposal, document, methodology, email, etc.';
COMMENT ON COLUMN agent_pinecone_sync.pinecone_id IS 'Vector ID in Pinecone index';

-- ============================================================================
-- 10. INDEXES FOR PERFORMANCE
-- ============================================================================

-- Chat sessions
CREATE INDEX IF NOT EXISTS idx_agent_chat_sessions_user ON agent_chat_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_agent_chat_sessions_client ON agent_chat_sessions(client_id);
CREATE INDEX IF NOT EXISTS idx_agent_chat_sessions_project ON agent_chat_sessions(project_id);
CREATE INDEX IF NOT EXISTS idx_agent_chat_sessions_folder ON agent_chat_sessions(folder);
CREATE INDEX IF NOT EXISTS idx_agent_chat_sessions_tags ON agent_chat_sessions USING GIN(tags);
CREATE INDEX IF NOT EXISTS idx_agent_chat_sessions_created ON agent_chat_sessions(created_at DESC);

-- Chat messages
CREATE INDEX IF NOT EXISTS idx_agent_chat_messages_session ON agent_chat_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_agent_chat_messages_created ON agent_chat_messages(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_chat_messages_role ON agent_chat_messages(role);

-- Full-text search on message content
CREATE INDEX IF NOT EXISTS idx_agent_chat_messages_content_fts 
  ON agent_chat_messages USING GIN(to_tsvector('english', content));

-- Artifacts
CREATE INDEX IF NOT EXISTS idx_agent_artifacts_session ON agent_artifacts(session_id);
CREATE INDEX IF NOT EXISTS idx_agent_artifacts_message ON agent_artifacts(message_id);
CREATE INDEX IF NOT EXISTS idx_agent_artifacts_type ON agent_artifacts(type);
CREATE INDEX IF NOT EXISTS idx_agent_artifacts_parent ON agent_artifacts(parent_artifact_id);

-- Templates
CREATE INDEX IF NOT EXISTS idx_agent_templates_user ON agent_templates(user_id);
CREATE INDEX IF NOT EXISTS idx_agent_templates_type ON agent_templates(type);
CREATE INDEX IF NOT EXISTS idx_agent_templates_active ON agent_templates(is_active);
CREATE INDEX IF NOT EXISTS idx_agent_templates_tags ON agent_templates USING GIN(tags);

-- Feedback
CREATE INDEX IF NOT EXISTS idx_agent_feedback_message ON agent_feedback(message_id);
CREATE INDEX IF NOT EXISTS idx_agent_feedback_user ON agent_feedback(user_id);
CREATE INDEX IF NOT EXISTS idx_agent_feedback_status ON agent_feedback(status);
CREATE INDEX IF NOT EXISTS idx_agent_feedback_created ON agent_feedback(created_at DESC);

-- User preferences
CREATE INDEX IF NOT EXISTS idx_agent_user_preferences_user ON agent_user_preferences(user_id);

-- Background jobs
CREATE INDEX IF NOT EXISTS idx_agent_background_jobs_user ON agent_background_jobs(user_id);
CREATE INDEX IF NOT EXISTS idx_agent_background_jobs_status ON agent_background_jobs(status);
CREATE INDEX IF NOT EXISTS idx_agent_background_jobs_type ON agent_background_jobs(job_type);
CREATE INDEX IF NOT EXISTS idx_agent_background_jobs_created ON agent_background_jobs(created_at DESC);

-- Notifications
CREATE INDEX IF NOT EXISTS idx_agent_notifications_user ON agent_notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_agent_notifications_read ON agent_notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_agent_notifications_created ON agent_notifications(created_at DESC);

-- Pinecone sync
CREATE INDEX IF NOT EXISTS idx_agent_pinecone_sync_source ON agent_pinecone_sync(source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_agent_pinecone_sync_pinecone_id ON agent_pinecone_sync(pinecone_id);

-- ============================================================================
-- 11. TRIGGERS FOR UPDATED_AT
-- ============================================================================

-- Update updated_at timestamp on sessions
CREATE OR REPLACE FUNCTION update_agent_session_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER agent_chat_sessions_updated
BEFORE UPDATE ON agent_chat_sessions
FOR EACH ROW
EXECUTE FUNCTION update_agent_session_timestamp();

-- Update updated_at timestamp on templates
CREATE TRIGGER agent_templates_updated
BEFORE UPDATE ON agent_templates
FOR EACH ROW
EXECUTE FUNCTION update_agent_session_timestamp();

-- Update updated_at timestamp on preferences
CREATE TRIGGER agent_user_preferences_updated
BEFORE UPDATE ON agent_user_preferences
FOR EACH ROW
EXECUTE FUNCTION update_agent_session_timestamp();

-- ============================================================================
-- 12. SAMPLE DATA (OPTIONAL - for testing)
-- ============================================================================

-- Insert sample template (you can customize or remove)
INSERT INTO agent_templates (user_id, type, name, description, colors, fonts, variables, tags)
VALUES (
  NULL, -- Global template
  'proposal',
  'Default Proposal Template',
  'Clean, professional proposal template',
  '{"primary": "#4F46E5", "secondary": "#10B981", "text": "#1F2937"}',
  '{"heading": "Inter", "body": "Open Sans"}',
  '["client_name", "project_title", "date", "advisor_name", "company_name"]',
  ARRAY['default', 'proposal']
) ON CONFLICT DO NOTHING;

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================

-- Log migration success
DO $$
BEGIN
  RAISE NOTICE '✅ Agentic AI Brain tables created successfully';
  RAISE NOTICE '📊 Tables created: 11';
  RAISE NOTICE '🔍 Indexes created: 30+';
  RAISE NOTICE '⚡ Triggers created: 3';
END $$;

